CREATE DATABASE BSR_ImportStock
USE BSR_ImportStock
SELECT * FROM Sales_Data

SELECT SUM(Sales) FROM Sales_Data
SELECT COUNT(BillID) FROM Sales_Data
SELECT COUNT(BillID) FROM Sales_Data WHERE Month(Date)=4

SELECT ROUND(((CAST(TOTAL_SALES_MTD AS Float)-CAST(TOTAL_SALES_PMTD AS FLOAT))/CAST(TOTAL_SALES_MTD AS Float))*100,2) AS MOM_SALES_Percentage
FROM(
SELECT
(SELECT SUM(Sales) FROM Sales_Data WHERE Month(Date)=4) AS TOTAL_SALES_MTD,
(SELECT SUM(Sales) FROM Sales_Data WHERE MONTH(Date)=3) AS TOTAL_SALES_PMTD
) AS SALES_SUMMARY

SELECT AVG(Sales) FROM Sales_Data WHERE MONTH(Date)=4
SELECT AVG(Sales) FROM Sales_Data WHERE MONTH(Date)=3





/*WITH Sales_MTD AS (
    SELECT SUM(Sales) AS TOTAL_SALES_MTD
    FROM Sales_Data
    WHERE MONTH(Date) = 4
),
Sales_PMTD AS (
    SELECT SUM(Sales) AS TOTAL_SALES_PMTD
    FROM Sales_Data
    WHERE MONTH(Date) = 3
)
SELECT 
    ROUND((smt.TOTAL_SALES_MTD - spt.TOTAL_SALES_PMTD) / spt.TOTAL_SALES_PMTD * 100, 2) AS MOM_SALES_Percentage
FROM 
    Sales_MTD smt, Sales_PMTD spt;
*/